# Default values for methode-article-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"

eksCluster: false

replicaCount: 2
image:
  repository: coco/methode-article-mapper
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 768Mi
  requests:
    memory: 384Mi
    cpu: "350m"
env:
  KAFKA_ENABLED: false
  DOCUMENT_STORE_API_ENABLED: false
  CONCORDANCE_API_ENABLED: false
ingress:
  enabled: "false"
