##this is an example deployment.yaml that should be customized in order to meet the configuration for app k8s deployment

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers: 
      - name: {{ .Values.service.name }} 
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAFKA_ENABLED
          value: "false"
        - name: KAFKA_PROXY_URL
          value: "kafka-rest-proxy:8080"
        - name: DOCUMENT_STORE_API_ENABLED
          value: "false"
        - name: DOCUMENT_STORE_API_URL
          value: "document-store-api:8080"
        - name: CONCORDANCE_API_ENABLED
          value: "false"
        - name: CONCORDANCE_API_URL
          value: "public-concordances-api:8080"
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host
        ports: 
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe: 
          tcpSocket: 
            port: 8080 
          initialDelaySeconds: 10
        readinessProbe: 
          httpGet: 
            path: "/__gtg" 
            port: 8080 
          initialDelaySeconds: 12
          periodSeconds: 30 
        resources: 
{{ toYaml .Values.resources | indent 12 }}

