name    'ft-methode_article_transformer'
version '${project.version}'
source 'UNKNOWN'
author 'ft'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'ft/common_pp_up', '1.0.x'
dependency 'ft/jdk', '1.0.x'
dependency 'ft/dropwizard', '2.0.x'
